(() => {
  'use strict';
  const API_URL='https://ofield-ai-api.luiseldorado110.workers.dev/';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const format=t=>esc(t).replace(/^###\s+(.+)$/gm,'<h4>$1</h4>').replace(/^##\s+(.+)$/gm,'<h3>$1</h3>').replace(/^#\s+(.+)$/gm,'<h2>$1</h2>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>');
  function architecturePrompt({idea,size,budget,type}){return `Actúa como un arquitecto profesional con experiencia en diseño residencial, planeación arquitectónica, distribución espacial y documentación conceptual.\n\nNo afirmes tener licencia profesional ni emitas autorización de construcción. Produce una propuesta arquitectónica conceptual de alta calidad para que después sea revisada por un arquitecto/ingeniero local.\n\nDATOS DEL PROYECTO\nTipo: ${type}\nTerreno / tamaño: ${size||'No especificado'}\nPresupuesto: ${budget||'No especificado'}\nSolicitud: ${idea}\n\nMÉTODO OBLIGATORIO\n1. Interpreta terreno, orientación, usuarios, necesidades y restricciones.\n2. Define zonificación: acceso, área pública, área privada, servicios, circulación y exteriores.\n3. Resuelve un recorrido lógico sin atravesar recámaras para llegar a otras zonas.\n4. Considera iluminación natural, ventilación cruzada, privacidad, orientación solar, relación interior-exterior y eficiencia de circulación.\n5. Declara supuestos cuando falten datos.\n6. No inventes medidas sin comprobar que caben.\n7. Comprueba coherencia aproximada entre áreas, terreno y retiros.\n8. Diferencia la distribución por nivel en viviendas de varios pisos.\n9. Decide la geometría conveniente de la planta: rectangular, L, U, patios, vacíos o retranqueos.\n10. Primero resuelve el diseño y después explica la solución.\n\nENTREGA SIEMPRE\n- Diagnóstico del terreno\n- Concepto arquitectónico\n- Programa arquitectónico con áreas aproximadas\n- Zonificación\n- Circulaciones y anchos orientativos\n- Distribución por planta\n- Puertas y ventanas\n- Iluminación y ventilación\n- Materiales y sistema constructivo conceptual\n- Fachada / lenguaje arquitectónico\n- Estrategia de crecimiento si aplica\n- Presupuesto conceptual por partidas si hay presupuesto\n- Riesgos, supuestos y datos faltantes\n- Qué debe dibujarse en el plano\n- Próximos pasos\n\nPara el plano describe la posición relativa de cada espacio (frente, fondo, izquierda, derecha, junto a, conectado con) y sus medidas aproximadas. No entregues solo una lista de habitaciones. Responde en español, profesional y fácil de entender.`;}
  async function handleArchitectureSubmit(event){
    const form=event.target;if(!form||form.id!=='projectForm')return;
    const type=document.getElementById('type')?.value||'';if(type!=='Arquitectura')return;
    event.preventDefault();event.stopImmediatePropagation();
    const idea=document.getElementById('idea')?.value.trim()||'',size=document.getElementById('size')?.value.trim()||'',budget=document.getElementById('budget')?.value.trim()||'',msg=document.getElementById('message'),btn=form.querySelector('button[type="submit"]');
    if(!idea){if(msg)msg.textContent='Escribe primero la idea del proyecto.';return}
    if(msg)msg.textContent='✦ Ofield AI está diseñando como arquitecto: analizando terreno, zonificación y circulación...';if(btn)btn.disabled=true;
    try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea:architecturePrompt({idea,size,budget,type})})});const d=await r.json();if(!r.ok||!d.result)throw new Error('No hubo respuesta de la IA');
      document.getElementById('resultSummary').textContent='Arquitectura · propuesta conceptual profesional.';
      document.getElementById('resultBox').innerHTML=`<div class="result-box"><h3>Proyecto arquitectónico conceptual</h3><div class="ai-answer">${format(d.result)}</div></div>`;
      document.getElementById('resultado').classList.remove('hidden');document.getElementById('resultado').scrollIntoView({behavior:'smooth'});
      const h=JSON.parse(localStorage.getItem('ofieldProjects')||'[]');h.unshift({type,idea,size,budget,answer:d.result,date:new Date().toLocaleString('es-MX')});localStorage.setItem('ofieldProjects',JSON.stringify(h.slice(0,8)));
      if(msg)msg.textContent='✓ Propuesta arquitectónica generada.';
    }catch(err){console.error('[Ofield AI arquitectura]',err);if(msg)msg.textContent='No se pudo generar la propuesta arquitectónica. Revisa la conexión con el Worker.';}finally{if(btn)btn.disabled=false;}
  }
  document.addEventListener('submit',handleArchitectureSubmit,true);
  const attach=()=>{const button=document.getElementById('openConceptPlan');if(!button)return false;button.removeAttribute('onclick');button.dataset.ofieldBound='1';button.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();const panel=document.getElementById('conceptPlanPanel');if(panel){panel.classList.remove('hidden');panel.scrollIntoView({behavior:'smooth',block:'center');}};return false;};return true;};
  const loadScript=(src,key,after)=>{if(window[key]){after?.();return;}window[key]=true;const script=document.createElement('script');script.src=src;script.defer=false;script.onload=()=>after?.();script.onerror=()=>console.error('[Ofield AI] No se pudo cargar:',src);document.head.appendChild(script);};
  const cleanLegacy=()=>{document.querySelectorAll('script[src*="plan-smart.js"],script[src*="plan-cad.js"],script[src*="corridor-cad.js"]').forEach(s=>s.remove());document.querySelectorAll('#conceptPlanPanel').forEach((panel,i)=>{if(i>0)panel.remove();});};
  const start=()=>{cleanLegacy();attach();loadScript('history-budget.js?v=4','__ofieldHistoryBudgetLoaded',()=>{loadScript('professional-plan.js?v=6','__ofieldProfessionalPlanLoaded',()=>{attach();});});let attempts=0;const retry=()=>{if(attach()||attempts++>=40)return;setTimeout(retry,200)};retry();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();