(() => {
  'use strict';
  const STYLE='ofield-plan-cad-complete';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const el=id=>document.getElementById(id);
  function css(){if(el(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
#conceptPlanPanel.ofield-cad{background:#f4f5f6;color:#151515}
.ofield-cad .cad-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.ofield-cad .cad-toolbar button{cursor:pointer}
.ofield-cad .cad-stage{background:#e4e5e7;border:1px solid #c5c7ca;border-radius:12px;padding:16px;overflow:auto}.ofield-cad .cad-sheets{display:flex;gap:18px;align-items:flex-start;min-width:max-content}.ofield-cad .cad-sheet{background:#fff;border:1px solid #aaa;box-shadow:0 4px 14px #0002;padding:8px}.ofield-cad svg{display:block;width:520px;height:auto;background:#fff;font-family:Arial,Helvetica,sans-serif}.ofield-cad .cad-title{font-size:16px;font-weight:700;fill:#111;text-anchor:middle}.ofield-cad .cad-sub{font-size:9px;fill:#444;text-anchor:middle}.ofield-cad .cad-label{font-size:11px;font-weight:700;fill:#111;text-anchor:middle;dominant-baseline:middle}.ofield-cad .cad-small{font-size:8px;fill:#444;text-anchor:middle}.ofield-cad .wall{stroke:#111;stroke-width:8;fill:#fff;stroke-linejoin:miter}.ofield-cad .iwall{stroke:#222;stroke-width:4;fill:#fff}.ofield-cad .thin{stroke:#555;stroke-width:1.2;fill:none}.ofield-cad .door{stroke:#111;stroke-width:1.3;fill:none}.ofield-cad .window{stroke:#23729a;stroke-width:4;fill:none}.ofield-cad .furn{stroke:#555;stroke-width:1;fill:#fafafa}.ofield-cad .car{stroke:#555;stroke-width:1.2;fill:#f1f1f1}.ofield-cad .dim{stroke:#333;stroke-width:1;fill:none}.ofield-cad .dimtxt{font-size:9px;font-weight:700;fill:#222;text-anchor:middle}.ofield-cad .axis{font-size:8px;font-weight:700;fill:#555;text-anchor:middle}.ofield-cad .note{font-size:8px;fill:#444}.ofield-cad .north{font-size:11px;font-weight:700;fill:#111;text-anchor:middle}.ofield-cad .schedule{background:#fff;border:1px solid #ccc;margin-top:14px;padding:14px}.ofield-cad table{width:100%;border-collapse:collapse}.ofield-cad th,.ofield-cad td{border:1px solid #ccc;padding:7px;text-align:left;font-size:13px}.ofield-cad th{background:#f0f0f0}.ofield-cad .cad-status{margin:8px 0}.ofield-cad .cad-disclaimer{font-size:12px;opacity:.8}.ofield-cad .hidden{display:none!important}
@media(max-width:900px){.ofield-cad svg{width:390px}}@media print{body *{visibility:hidden!important}#conceptPlanPanel,#conceptPlanPanel *{visibility:visible!important}#conceptPlanPanel{position:absolute!important;left:0!important;top:0!important;width:100%!important;background:#fff!important}.ofield-cad .cad-stage{background:#fff!important;border:0!important;padding:0!important;overflow:visible!important}.ofield-cad .cad-sheets{gap:5px!important}.ofield-cad .cad-sheet{box-shadow:none!important;page-break-inside:avoid!important}.ofield-cad svg{width:31vw!important;max-width:none!important}}
`;document.head.appendChild(s)}
  function panel(){let p=el('conceptPlanPanel');if(p){css();return p}const sec=el('herramientas');if(!sec)return null;p=document.createElement('div');p.id='conceptPlanPanel';p.className='budget-panel hidden ofield-cad';p.innerHTML=`
<div class="budget-top"><div><div class="section-tag">ARQUITECTURA / PLANO 2D</div><h3>Generador completo de plano conceptual</h3><p>Distribución inteligente con circulación, muros, puertas, ventanas, mobiliario, cotas, ejes, norte, cuadro de áreas y roof garden.</p></div><button id="closePlanCad" class="secondary" type="button">Cerrar</button></div>
<div class="form-grid"><div><label for="cadL">Frente del terreno (m)</label><input id="cadL" type="number" min="3" step="0.1" value="8"></div><div><label for="cadW">Fondo del terreno (m)</label><input id="cadW" type="number" min="5" step="0.1" value="20"></div></div>
<div class="form-grid"><div><label for="cadLevels">Niveles</label><select id="cadLevels"><option value="1">1 planta</option><option value="2" selected>2 plantas</option><option value="3">2 plantas + Roof Garden</option></select></div><div><label for="cadRooms">Recámaras</label><input id="cadRooms" type="number" min="1" max="6" value="3"></div></div>
<div class="form-grid"><div><label for="cadBaths">Baños</label><input id="cadBaths" type="number" min="1" max="5" value="2"></div><div><label for="cadCars">Autos</label><input id="cadCars" type="number" min="0" max="3" value="2"></div></div>
<label for="cadNeeds">Necesidades y espacios especiales</label><textarea id="cadNeeds" rows="3" placeholder="Ej. cocina abierta, patio, lavandería, estudio, terraza, jardín..."></textarea>
<div class="cad-toolbar"><button id="generateCad" class="primary" type="button">Generar plano ✦</button><button id="printCad" class="secondary" type="button">▣ Imprimir / PDF</button><button id="saveCad" class="secondary" type="button">＋ Guardar plano</button><button id="closeCad2" class="secondary" type="button">Cerrar</button></div><p id="cadMsg" class="message"></p><div id="cadResult"></div>`;sec.appendChild(p);css();
    el('closePlanCad').onclick=()=>p.classList.add('hidden');el('closeCad2').onclick=()=>p.classList.add('hidden');el('generateCad').onclick=generate;el('printCad').onclick=()=>window.print();el('saveCad').onclick=save;return p}
  function ensureOpen(){const p=panel();if(!p)return; p.classList.remove('hidden');p.scrollIntoView({behavior:'smooth',block:'center'})}
  function bind(){css();panel();const b=el('openConceptPlan');if(b){b.onclick=e=>{e.preventDefault();e.stopPropagation();ensureOpen()};b.removeAttribute('onclick')}document.addEventListener('click',e=>{if(e.target.closest('#openConceptPlan')){e.preventDefault();ensureOpen()}})}
  function line(a,b,c,d,k='thin'){return `<line class="${k}" x1="${a}" y1="${b}" x2="${c}" y2="${d}"/>`}
  function rect(x,y,w,h,k='furn',r=0){return `<rect class="${k}" x="${x}" y="${y}" width="${Math.max(1,w)}" height="${Math.max(1,h)}" ${r?`rx="${r}"`:''}/>`}
  function text(x,y,t,k='cad-label'){return `<text class="${k}" x="${x}" y="${y}">${esc(t)}</text>`}
  function room(x,y,w,h,n,sub=''){return `${rect(x,y,w,h,'iwall')} ${text(x+w/2,y+h/2-3,n)}${sub?text(x+w/2,y+h/2+10,sub,'cad-small'):''}`}
  function bed(x,y,w=58,h=38){return `${rect(x,y,w,h,'furn',3)}${line(x,y+h*.25,x+w,y+h*.25)}${rect(x+4,y+4,w*.38,h*.16,'furn',2)}${rect(x+w*.58,y+4,w*.38,h*.16,'furn',2)}`}
  function sofa(x,y,w=76,h=34){return `${rect(x,y,w,h,'furn',4)}${line(x+6,y+h*.3,x+w-6,y+h*.3)}`}
  function table(x,y,w=58,h=30){return `${rect(x,y,w,h,'furn',4)}<circle class="furn" cx="${x-8}" cy="${y+h/2}" r="6"/><circle class="furn" cx="${x+w+8}" cy="${y+h/2}" r="6"/>`}
  function car(x,y,w=58,h=88){return `${rect(x,y,w,h,'car',10)}${rect(x+w*.18,y+h*.16,w*.64,h*.38,'furn',6)}<circle class="furn" cx="${x+w*.2}" cy="${y+h*.84}" r="6"/><circle class="furn" cx="${x+w*.8}" cy="${y+h*.84}" r="6"/>`}
  function doorH(x,y,w=26){return `${line(x,y,x+w,y,'door')}<path class="door" d="M ${x} ${y} A ${w} ${w} 0 0 1 ${x+w} ${y-w}"/>`}
  function doorV(x,y,w=26){return `${line(x,y,x,y+w,'door')}<path class="door" d="M ${x} ${y} A ${w} ${w} 0 0 0 ${x+w} ${y+w}"/>`}
  function windowH(x,y,w=60){return line(x,y,x+w,y,'window')}
  function windowV(x,y,h=60){return line(x,y,x,y+h,'window')}
  function dim(L,W,x,y,w,h){let s='';s+=line(x,y-28,x+w,y-28,'dim')+line(x,y-34,x,y-22,'dim')+line(x+w,y-34,x+w,y-22,'dim')+text(x+w/2,y-36,L.toFixed(2)+' m','dimtxt');s+=line(x-28,y,x-28,y+h,'dim')+line(x-34,y,x-22,y,'dim')+line(x-34,y+h,x-22,y+h,'dim')+`<text class="dimtxt" transform="translate(${x-40},${y+h/2}) rotate(-90)">${W.toFixed(2)} m</text>`;return s}
  function north(x,y){return `<g><line class="thin" x1="${x}" y1="${y+28}" x2="${x}" y2="${y-10}"/><path d="M ${x} ${y-22} L ${x-7} ${y-8} L ${x+7} ${y-8} Z" fill="#111"/>${text(x,y-31,'N','north')}</g>`}
  function axes(x,y,w,h){let s='';for(let i=0;i<5;i++){let xx=x+w*i/4;s+=`<circle cx="${xx}" cy="${y-77}" r="9" fill="#fff" stroke="#555"/>`+text(xx,y-74,String(i+1),'axis')}for(let i=0;i<6;i++){let yy=y+h*i/5;s+=`<circle cx="${x-62}" cy="${yy}" r="9" fill="#fff" stroke="#555"/>`+text(x-62,yy+3,String.fromCharCode(65+i),'axis')}return s}
  function parseNeeds(s){const t=s.toLowerCase();return{patio:/patio|jard[ií]n/.test(t),laundry:/lavander[ií]a|cuarto de lavado/.test(t),study:/estudio|oficina/.test(t),terrace:/terraza/.test(t),openKitchen:/cocina abierta|cocina integrada/.test(t)}}
  function makeSheet(level,L,W,rooms,baths,cars,needs,roof=false){const VW=620,VH=820,x=105,y=150,w=360,h=Math.max(480,Math.min(610,W/L*w));let s=`<svg viewBox="0 0 ${VW} ${VH}" role="img" aria-label="Plano ${roof?'roof garden':'planta '+level}"><rect width="620" height="820" fill="#fff"/>`;s+=text(310,28,roof?'PLANTA ROOF GARDEN':`PLANTA ${level}`,'cad-title')+text(310,47,`${L.toFixed(2)} × ${W.toFixed(2)} m`,'cad-sub')+axes(x,y,w,h)+dim(L,W,x,y,w,h)+north(565,92)+`<rect class="wall" x="${x}" y="${y}" width="${w}" height="${h}"/>`;
    const n=parseNeeds(needs);
    if(roof){s+=room(x+5,y+5,w-10,h*.28-10,'TERRAZA / ROOF GARDEN');s+=room(x+5,y+h*.28+5,w*.55-10,h*.30-10,'ÁREA SOCIAL');s+=room(x+w*.55+5,y+h*.28+5,w*.45-10,h*.30-10,'PÉRGOLA');s+=room(x+5,y+h*.58+5,w*.45-10,h*.42-10,'SERVICIO');s+=room(x+w*.45+5,y+h*.58+5,w*.55-10,h*.42-10,'ESCALERA / VACÍO');s+=table(x+40,y+h*.38)+doorH(x+w*.45,y+h*.58)+windowH(x+25,y+h-3,90)}
    else if(level===1){const garage=Math.min(120,h*.22), socialY=y+garage, corridor=62, bottom=y+h*.63; s+=room(x+5,y+5,w-10,garage-10,'COCHERA',`${cars} auto(s)`);if(cars>0){const count=Math.min(cars,2),gap=w/(count+1);for(let i=0;i<count;i++)s+=car(x+gap*(i+1)-29,y+18)}s+=room(x+5,socialY+5,w*.34-10,bottom-socialY-10,'SALA');s+=sofa(x+22,socialY+30);s+=room(x+w*.34+5,socialY+5,w*.30-10,bottom-socialY-10,'COMEDOR');s+=table(x+w*.34+30,socialY+42);s+=room(x+w*.64+5,socialY+5,w*.36-10,bottom-socialY-10,'COCINA',n.openKitchen?'ABIERTA':'');const cy=bottom;const cw=62;s+=room(x+5,cy+5,cw-10,h-(cy-y)-10,'PASILLO','circulación');s+=room(x+cw+5,cy+5,w*.25-10,h-(cy-y)-10,'BAÑO');s+=room(x+cw+w*.25+5,cy+5,w*.28-10,h-(cy-y)-10,'ESCALERA');let special=n.laundry?'LAVANDERÍA':n.study?'ESTUDIO':n.patio?'PATIO':'PATIO / SERVICIO';s+=room(x+cw+w*.53+5,cy+5,w*.47-10,h-(cy-y)-10,special);s+=doorH(x+w*.48,socialY,28)+doorH(x+cw,cy+30,24)+doorV(x+cw+20,cy+25)+windowH(x+18,y+garage,72)+windowV(x+w,socialY+25,72)+windowH(x+w*.67,y+h-3,70)}
    else {const hall=58; s+=room(x+5,y+5,w*.68-10,h*.14-10,'ESTAR / PASILLO');s+=room(x+w*.68+5,y+5,w*.32-10,h*.14-10,'BAÑO');const usableY=y+h*.14, rows=Math.ceil(rooms/2), rh=(h*(.86))/rows;for(let i=0;i<rooms;i++){const col=i%2,row=Math.floor(i/2),xx=x+hall+col*(w-hall)/2,yy=usableY+row*rh;const ww=(w-hall)/2;s+=room(xx+5,yy+5,ww-10,rh-10,'RECÁMARA '+(i+1));s+=bed(xx+ww*.25,yy+rh*.42);s+=windowH(xx+18,yy+rh-3,55);s+=doorH(xx,yy+rh*.52,24)}s+=room(x+5,usableY+5,hall-10,h*.86-10,'PASILLO','circulación');s+=room(x+hall+5,y+h*.86+5,w*.34-10,h*.14-10,'BAÑO');s+=room(x+hall+w*.34+5,y+h*.86+5,w*.30-10,h*.14-10,'ESCALERA');s+=room(x+hall+w*.64+5,y+h*.86+5,w*.36-10,h*.14-10,n.terrace?'TERRAZA':'ESTAR');s+=doorH(x+hall,usableY+28,24)}
    s+=`<text class="note" x="${x}" y="${y+h+38}">PLANO CONCEPTUAL · NO EJECUTIVO · VERIFICAR REGLAMENTO, ESTRUCTURA E INSTALACIONES</text></svg>`;return s}
  function areaTable(L,W,rooms,levels,cars,baths){const total=L*W;let rows=[['Terreno',total.toFixed(2)+' m²'],['Plantas',levels===3?'2 + Roof Garden':String(levels)],['Recámaras',String(rooms)],['Baños',String(baths)],['Cochera',cars?cars+' auto(s)':'Sin cochera']];return `<div class="schedule"><h3>Cuadro de datos del proyecto</h3><table><thead><tr><th>Dato</th><th>Valor</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td></tr>`).join('')}</tbody></table><p class="cad-disclaimer">Las áreas y distribuciones son orientativas. El proyecto ejecutivo requiere revisión y firma de profesionales y cumplimiento de normativa local.</p></div>`}
  function generate(){const p=panel();if(!p)return;const L=+el('cadL').value||0,W=+el('cadW').value||0,levels=+el('cadLevels').value,rooms=+el('cadRooms').value,baths=+el('cadBaths').value,cars=+el('cadCars').value,needs=el('cadNeeds').value.trim();const msg=el('cadMsg'),out=el('cadResult');if(L<3||W<5){msg.textContent='Ingresa medidas válidas: mínimo 3 m de frente y 5 m de fondo.';return}msg.textContent='✦ Organizando espacios, pasillos, puertas, ventanas y mobiliario...';const roof=levels===3;const count=roof?2:levels;let sheets='';for(let i=1;i<=count;i++)sheets+=`<div class="cad-sheet">${makeSheet(i,L,W,rooms,baths,cars,needs,false)}</div>`;if(roof)sheets+=`<div class="cad-sheet">${makeSheet(3,L,W,rooms,baths,cars,needs,true)}</div>`;out.innerHTML=`<div class="cad-stage"><div class="cad-sheets">${sheets}</div></div>${areaTable(L,W,rooms,levels,cars,baths)}`;msg.textContent='✓ Plano conceptual completo generado.';out.dataset.plan=JSON.stringify({L,W,levels,rooms,baths,cars,needs,created:new Date().toISOString()});}
  function save(){const out=el('cadResult');if(!out?.dataset.plan){el('cadMsg').textContent='Genera un plano primero.';return}let arr=[];try{arr=JSON.parse(localStorage.getItem('ofield_cad_plans')||'[]')}catch{};const data=JSON.parse(out.dataset.plan);arr.unshift(data);localStorage.setItem('ofield_cad_plans',JSON.stringify(arr.slice(0,20)));el('cadMsg').textContent='✓ Plano guardado en este navegador.'}
  function start(){bind();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();