(() => {
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const wait=fn=>{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn();};
  const num=id=>Number(document.getElementById(id)?.value)||0;
  const txt=(x,y,t,cls='lbl')=>`<text class="${cls}" x="${x}" y="${y}">${esc(t)}</text>`;
  const rect=(x,y,w,h,cls='room')=>`<rect class="${cls}" x="${x}" y="${y}" width="${w}" height="${h}"/>`;
  const line=(x1,y1,x2,y2,cls='thin')=>`<line class="${cls}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`;
  function styles(){if(document.getElementById('smart-cad-style'))return;const s=document.createElement('style');s.id='smart-cad-style';s.textContent=`#cadV2Result .smart-sheet{background:#fff;border:1px solid #bbb;padding:10px;margin:0 0 18px;overflow:auto}#cadV2Result .smart-svg{width:100%;min-width:760px;height:auto;font-family:Arial,sans-serif}.smart-svg .room{fill:#fff;stroke:#111;stroke-width:3}.smart-svg .thin{stroke:#333;stroke-width:1.4;fill:none}.smart-svg .wall{fill:none;stroke:#111;stroke-width:8}.smart-svg .door{stroke:#111;stroke-width:1.3;fill:none}.smart-svg .win{stroke:#1476b8;stroke-width:5}.smart-svg .lbl{font-size:13px;font-weight:700;text-anchor:middle;dominant-baseline:middle;fill:#111}.smart-svg .sub{font-size:9px;text-anchor:middle;fill:#444}.smart-svg .dim{font-size:10px;font-weight:700;text-anchor:middle;fill:#222}.smart-svg .axis{font-size:9px;font-weight:700;text-anchor:middle;fill:#555}.smart-svg .furn{fill:#fafafa;stroke:#555;stroke-width:1.1}.smart-svg .note{font-size:9px;fill:#333}@media print{body *{visibility:hidden!important}#conceptPlanPanel,#conceptPlanPanel *{visibility:visible!important}#conceptPlanPanel{position:absolute!important;left:0;top:0;width:100%!important;background:#fff!important}.smart-sheet{page-break-inside:avoid!important;border:0!important}.smart-svg{min-width:0!important}}`;document.head.appendChild(s)}
  function room(x,y,w,h,name,sub=''){return rect(x,y,w,h)+txt(x+w/2,y+h/2-4,name,'lbl')+(sub?txt(x+w/2,y+h/2+12,sub,'sub'):'')}
  function door(x,y,w){return line(x,y,x+w,y,'door')+`<path class="door" d="M ${x} ${y} A ${w} ${w} 0 0 1 ${x+w} ${y-w}"/>`}
  function win(x,y,w,vertical=false){return line(x,y,vertical?x:x+w,vertical?y+w:y,'win')}
  function sofa(x,y){return rect(x,y,72,32,'furn')+line(x+8,y+16,x+64,y+16,'thin')}
  function bed(x,y){return rect(x,y,64,38,'furn')+line(x,y+12,x+64,y+12,'thin')+rect(x+5,y+3,22,8,'furn')+rect(x+37,y+3,22,8,'furn')}
  function car(x,y){return `<g><rect class="furn" x="${x}" y="${y}" width="54" height="88" rx="12"/><rect class="furn" x="${x+10}" y="${y+15}" width="34" height="30" rx="7"/><circle class="furn" cx="${x+11}" cy="${y+73}" r="6"/><circle class="furn" cx="${x+43}" cy="${y+73}" r="6"/></g>`}
  function dims(x,y,w,h,L,W){return line(x,y-24,x+w,y-24,'thin')+line(x,y-30,x,y-18,'thin')+line(x+w,y-30,x+w,y-18,'thin')+txt(x+w/2,y-34,L.toFixed(2)+' m','dim')+line(x-24,y,x-24,y+h,'thin')+line(x-30,y,x-18,y,'thin')+line(x-30,y+h,x-18,y+h,'thin')+`<text class="dim" transform="translate(${x-37},${y+h/2}) rotate(-90)">${W.toFixed(2)} m</text>`}
  function svg(level,L,W,rooms,baths,cars,needs,roof){const fw=500,fh=Math.max(500,Math.min(640,fw*W/L)),x=120,y=125,vw=760,vh=fh+210;let s=`<svg class="smart-svg" viewBox="0 0 ${vw} ${vh}"><rect width="100%" height="100%" fill="#fff"/>${txt(vw/2,28,roof?'PLANTA ROOF GARDEN':`PLANTA ${level}`,'lbl')}${txt(vw/2,48,`${L.toFixed(2)} × ${W.toFixed(2)} m`,'sub')}`;for(let i=0;i<5;i++){let xx=x+i*fw/4;s+=`<circle cx="${xx}" cy="${y-58}" r="9" fill="#fff" stroke="#555"/>${txt(xx,y-55,String(i+1),'axis')}`}for(let i=0;i<6;i++){let yy=y+i*fh/5;s+=`<circle cx="${x-58}" cy="${yy}" r="9" fill="#fff" stroke="#555"/>${txt(x-58,yy+3,String.fromCharCode(65+i),'axis')}`}s+=dims(x,y,fw,fh,L,W)+`<rect class="wall" x="${x}" y="${y}" width="${fw}" height="${fh}"/>`;
    const n=(needs||'').toLowerCase();
    if(roof){s+=room(x+8,y+8,fw-16,fh*.28-16,'ROOF GARDEN','área verde / terraza');s+=room(x+8,y+fh*.28+8,fw*.55-16,fh*.32-16,'TERRAZA');s+=room(x+fw*.55+8,y+fh*.28+8,fw*.45-16,fh*.32-16,'PÉRGOLA');s+=room(x+8,y+fh*.60+8,fw*.45-16,fh*.40-16,'SERVICIO');s+=room(x+fw*.45+8,y+fh*.60+8,fw*.55-16,fh*.40-16,'ESCALERA / VACÍO');}
    else if(level===1){const front=Math.min(125,fh*.23),socialY=y+front,mid=y+fh*.53,garageW=fw*.42; s+=room(x+8,y+8,garageW-16,front-16,'COCHERA',cars+' auto(s)');s+=room(x+garageW+8,y+8,fw-garageW-16,front-16,'ACCESO / JARDÍN');for(let i=0;i<Math.min(cars,2);i++)s+=car(x+garageW*.15+i*garageW*.48,y+18);const openKitchen=n.includes('cocina abierta')||n.includes('cocina abierta');s+=room(x+8,socialY+8,fw*.34-16,mid-socialY-16,'SALA');s+=sofa(x+25,socialY+35);s+=room(x+fw*.34+8,socialY+8,fw*.30-16,mid-socialY-16,'COMEDOR');s+=room(x+fw*.64+8,socialY+8,fw*.36-16,mid-socialY-16,openKitchen?'COCINA ABIERTA':'COCINA');s+=room(x+8,mid+8,fw*.22-16,fh-(mid-y)-16,'BAÑO');s+=room(x+fw*.22+8,mid+8,fw*.20-16,fh-(mid-y)-16,'ESCALERA');const patioName=n.includes('lavander')?'LAVANDERÍA + PATIO':'PATIO / SERVICIO';s+=room(x+fw*.42+8,mid+8,fw*.58-16,fh-(mid-y)-16,patioName);s+=door(x+garageW,y+front,30)+door(x+fw*.22,mid+30,25)+door(x+fw*.42,mid+35,25);s+=win(x+20,y+front-3,90)+win(x+fw-3,socialY+25,70,true)+win(x+fw*.58,y+fh-3,90);}
    else {const head=78;s+=room(x+8,y+8,fw*.55-16,head-16,'ESTAR / DISTRIBUIDOR');s+=room(x+fw*.55+8,y+8,fw*.45-16,head-16,'BAÑO');const available=fh-head,rows=Math.max(2,Math.ceil(rooms/2)),rh=available/rows;for(let i=0;i<rooms;i++){const col=i%2,row=Math.floor(i/2),xx=x+col*fw/2,yy=y+head+row*rh;s+=room(xx+8,yy+8,fw/2-16,rh-16,'RECÁMARA '+(i+1));s+=bed(xx+fw/4-32,yy+rh*.42);s+=win(xx+18,yy+rh-4,60)+door(xx,yy+rh*.5,24)}const by=y+head+Math.ceil(rooms/2)*rh;s+=room(x+8,by+8,fw*.28-16,fh-(by-y)-16,'BAÑO');s+=room(x+fw*.28+8,by+8,fw*.24-16,fh-(by-y)-16,'ESCALERA');s+=room(x+fw*.52+8,by+8,fw*.48-16,fh-(by-y)-16,n.includes('estudio')?'ESTUDIO':'ESTAR FAMILIAR');}
    s+=`<text class="note" x="${x}" y="${y+fh+35}">N ↑  CONCEPTO / DISTRIBUCIÓN ORIENTATIVA</text></svg>`;return s}
  function generate(){styles();const L=num('cadL'),W=num('cadW'),levels=num('cadLevels'),rooms=num('cadRooms'),baths=num('cadBaths'),cars=num('cadCars'),needs=document.getElementById('cadNeeds')?.value.trim()||'';if(!L||!W){const m=document.getElementById('cadV2Msg');if(m)m.textContent='Ingresa frente y fondo del terreno.';return}const result=document.getElementById('cadV2Result'),msg=document.getElementById('cadV2Msg');if(msg)msg.textContent='✦ Generando distribución inteligente...';const sheets=[];for(let i=1;i<=Math.min(levels,2);i++)sheets.push(`<div class="smart-sheet"><div>${svg(i,L,W,rooms,baths,cars,needs,false)}</div></div>`);if(levels===3)sheets.push(`<div class="smart-sheet"><div>${svg(3,L,W,rooms,baths,cars,needs,true)}</div></div>`);result.innerHTML=`<div class="cad-v2-wrap">${sheets.join('')}</div><div class="budget-download"><button id="smartPrint" class="primary" type="button">▣ Imprimir / Guardar PDF</button></div><p class="message">⚠️ Distribución conceptual. Las dimensiones, estructura, instalaciones, ventilación, retiros y normativa deben verificarse profesionalmente.</p>`;document.getElementById('smartPrint').onclick=()=>window.print();if(msg)msg.textContent='✓ Plano generado con distribución inteligente.'}
  wait(()=>{const hook=()=>{const b=document.getElementById('generateCadV2');if(!b){setTimeout(hook,300);return}b.onclick=generate;const open=document.getElementById('openConceptPlan');if(open)open.onclick=()=>{const p=document.getElementById('conceptPlanPanel');if(p){p.classList.remove('hidden');p.scrollIntoView({behavior:'smooth',block:'center'})}}};hook()});
})();