(() => {
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const $=id=>document.getElementById(id);
const css=()=>{if($('ofieldProfessionalPlanStyle'))return;const s=document.createElement('style');s.id='ofieldProfessionalPlanStyle';s.textContent=`
#conceptPlanPanel.ofield-prof{background:#151515;color:#eee}.ofield-prof .prof-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.ofield-prof .prof-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ofield-prof label{display:block;margin:10px 0 6px}.ofield-prof input,.ofield-prof select,.ofield-prof textarea{width:100%;box-sizing:border-box;background:#202020;color:#eee;border:1px solid #444;border-radius:8px;padding:11px}.ofield-prof input:focus,.ofield-prof select:focus,.ofield-prof textarea:focus{outline:2px solid #caa74a;border-color:#caa74a}.ofield-prof .prof-tools{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.ofield-prof .sheet-wrap{margin-top:18px;background:#3b3b3b;border:1px solid #555;border-radius:12px;padding:18px;overflow:auto}.ofield-prof .sheet{background:#fff;color:#111;width:1000px;min-height:760px;margin:auto;padding:24px;box-sizing:border-box;position:relative;font-family:Arial,Helvetica,sans-serif}.ofield-prof svg{width:100%;height:auto;display:block}.ofield-prof .wall{stroke:#111;stroke-width:12;fill:#fff}.ofield-prof .iw{stroke:#111;stroke-width:6;fill:none}.ofield-prof .thin{stroke:#444;stroke-width:1.5;fill:none}.ofield-prof .dim{stroke:#222;stroke-width:1;fill:none}.ofield-prof .door{stroke:#111;stroke-width:1.5;fill:none}.ofield-prof .win{stroke:#1876a3;stroke-width:5}.ofield-prof .furn{stroke:#555;stroke-width:1.4;fill:#fafafa}.ofield-prof .label{font-size:13px;font-weight:700;text-anchor:middle}.ofield-prof .small{font-size:9px;fill:#444;text-anchor:middle}.ofield-prof .dimt{font-size:10px;font-weight:700;text-anchor:middle}.ofield-prof .axis{font-size:9px;font-weight:700;text-anchor:middle}.ofield-prof .title{font-size:20px;font-weight:700;text-anchor:middle}.ofield-prof .note{font-size:9px;fill:#555}.ofield-prof .tb{border:2px solid #111;margin-top:10px;display:grid;grid-template-columns:1fr 1fr 1fr 1fr}.ofield-prof .tb div{border-right:1px solid #111;padding:7px;font-size:10px}.ofield-prof .tb div:last-child{border:0}.ofield-prof .areas{margin-top:12px;border-collapse:collapse;width:100%;font-size:11px;background:#fff;color:#111}.ofield-prof .areas th,.ofield-prof .areas td{border:1px solid #999;padding:6px}.ofield-prof .areas th{background:#eee}.ofield-prof .disclaimer{color:#bbb;font-size:12px;margin-top:10px}.ofield-prof .hidden{display:none!important}@media(max-width:700px){.ofield-prof .prof-grid{grid-template-columns:1fr}.ofield-prof .sheet{width:900px}}@media print{body *{visibility:hidden!important}#conceptPlanPanel,#conceptPlanPanel *{visibility:visible!important}#conceptPlanPanel{position:absolute!important;left:0;top:0;width:100%!important;background:#fff!important}.ofield-prof .sheet-wrap{background:#fff!important;border:0!important;padding:0!important;overflow:visible!important}.ofield-prof .sheet{box-shadow:none!important;width:100%!important}}
`;document.head.appendChild(s)};
function build(){css();let p=$('conceptPlanPanel');if(!p){const sec=$('herramientas');if(!sec)return;p=document.createElement('section');p.id='conceptPlanPanel';p.className='budget-panel hidden ofield-prof';sec.appendChild(p)}p.innerHTML=`<div class="prof-head"><div><div class="section-tag">ARQUITECTURA / PROYECTO CONCEPTUAL</div><h3>Generador de plano arquitectónico</h3><p>Primero organiza la circulación y zonificación; después dibuja una lámina 2D con convenciones arquitectónicas.</p></div><button id="profClose" class="secondary" type="button">Cerrar</button></div><div class="prof-grid"><div><label>Frente del terreno (m)</label><input id="profL" type="number" min="3" step="0.1" value="8"></div><div><label>Fondo del terreno (m)</label><input id="profW" type="number" min="5" step="0.1" value="20"></div><div><label>Niveles</label><select id="profLevels"><option value="1">1 planta</option><option value="2" selected>2 plantas</option><option value="3">2 plantas + roof garden</option></select></div><div><label>Recámaras</label><input id="profRooms" type="number" min="1" max="6" value="3"></div><div><label>Baños</label><input id="profBaths" type="number" min="1" max="5" value="2"></div><div><label>Autos</label><input id="profCars" type="number" min="0" max="3" value="2"></div></div><label>Necesidades especiales</label><textarea id="profNeeds" rows="3" placeholder="Cocina abierta, patio, lavandería, estudio, terraza..."></textarea><div class="prof-tools"><button id="profGenerate" class="primary" type="button">Generar plano ✦</button><button id="profPrint" class="secondary" type="button">▣ Guardar PDF</button><button id="profSave" class="secondary" type="button">＋ Guardar plano</button></div><p id="profMsg" class="message"></p><div id="profResult"></div>`;
$('profClose').onclick=()=>p.classList.add('hidden');$('profGenerate').onclick=generate;$('profPrint').onclick=()=>window.print();$('profSave').onclick=save;return p}
function open(){const p=build();if(p){p.classList.remove('hidden');p.scrollIntoView({behavior:'smooth',block:'center'})}}
function room(x,y,w,h,name){return `<rect class="iw" x="${x}" y="${y}" width="${w}" height="${h}"/><text class="label" x="${x+w/2}" y="${y+h/2}">${esc(name)}</text>`}
function door(x,y,r=24){return `<path class="door" d="M ${x} ${y} A ${r} ${r} 0 0 1 ${x+r} ${y-r}"/>`}
function win(x,y,w){return `<line class="win" x1="${x}" y1="${y}" x2="${x+w}" y2="${y}"/>`}
function bed(x,y){return `<rect class="furn" x="${x}" y="${y}" width="58" height="38"/><line class="thin" x1="${x}" y1="${y+11}" x2="${x+58}" y2="${y+11}"/>`}
function sofa(x,y){return `<rect class="furn" x="${x}" y="${y}" width="78" height="34" rx="5"/>`}
function kitchen(x,y,w){return `<rect class="furn" x="${x}" y="${y}" width="${w}" height="24"/><line class="thin" x1="${x+15}" y1="${y}" x2="${x+15}" y2="${y+24}"/><line class="thin" x1="${x+35}" y1="${y}" x2="${x+35}" y2="${y+24}"/>`}
function car(x,y){return `<rect class="furn" x="${x}" y="${y}" width="45" height="76" rx="8"/><circle class="furn" cx="${x+10}" cy="${y+62}" r="5"/><circle class="furn" cx="${x+35}" cy="${y+62}" r="5"/>`}
function plan(level,L,W,rooms,baths,cars,needs){const vw=1000,vh=650,x=180,y=110,w=620,h=390;let s=`<svg viewBox="0 0 ${vw} ${vh}" aria-label="Plano arquitectónico conceptual"><rect width="1000" height="650" fill="#fff"/>`;
s+=`<text class="title" x="500" y="32">OFIELD AI · PLANTA ${level}</text><text class="small" x="500" y="50">PLANO ARQUITECTÓNICO CONCEPTUAL · ESCALA GRÁFICA 1:100</text>`;
for(let i=0;i<6;i++){const xx=x+i*w/5;s+=`<circle cx="${xx}" cy="75" r="11" fill="#fff" stroke="#555"/><text class="axis" x="${xx}" y="78">${i+1}</text>`}for(let i=0;i<5;i++){const yy=y+i*h/4;s+=`<circle cx="145" cy="${yy}" r="11" fill="#fff" stroke="#555"/><text class="axis" x="145" y="${yy+3}">${String.fromCharCode(65+i)}</text>`}
s+=`<rect class="wall" x="${x}" y="${y}" width="${w}" height="${h}"/>`;
if(level===1){const g=90, social=150, serv=150;s+=room(x+8,y+8,w-16,g-16,'COCHERA');for(let i=0;i<Math.min(cars,2);i++)s+=car(x+125+i*90,y+18);s+=room(x+8,y+g+8,w*.38-16,social-16,'SALA');s+=sofa(x+35,y+g+45);s+=room(x+w*.38+8,y+g+8,w*.28-16,social-16,'COMEDOR');s+=room(x+w*.66+8,y+g+8,w*.34-16,social-16,'COCINA');s+=kitchen(x+w*.68,y+g+25,w*.28);const sy=y+g+social;s+=room(x+8,sy+8,90,h-g-social-16,'PASILLO');s+=room(x+106,sy+8,w*.22-12,h-g-social-16,'BAÑO');s+=room(x+w*.22+98,sy+8,w*.22-12,h-g-social-16,'ESCALERA ↑');const special=/lavander|patio|jard/i.test(needs)?'PATIO / SERVICIO':'SERVICIO';s+=room(x+w*.44+98,sy+8,w*.56-114,h-g-social-16,special);s+=door(x+w*.38,y+g)+door(x+98,sy+40)+win(x+30,y+h-2,85)+win(x+w-95,y+g+20,65)}
else{const hall=92, top=120, bottom=90; s+=room(x+8,y+8,w*.7-12,top-16,'ESTAR / PASILLO');s+=room(x+w*.7+8,y+8,w*.3-16,top-16,'BAÑO');const usableY=y+top;const n=Math.max(1,rooms);const cols=2, rows=Math.ceil(n/cols);const rw=(w-hall)/2,rh=(h-top-bottom)/rows;for(let i=0;i<n;i++){const c=i%2,r=Math.floor(i/2),xx=x+hall+c*rw,yy=usableY+r*rh;s+=room(xx+4,yy+4,rw-8,rh-8,'RECÁMARA '+(i+1));s+=bed(xx+rw/2-29,yy+rh/2-19);s+=win(xx+18,yy+rh-3,55);s+=door(xx,yy+rh/2)}s+=room(x+8,usableY+8,hall-16,h-top-bottom-16,'PASILLO');s+=room(x+hall+8,y+h-bottom+8,w*.28-16,bottom-16,'BAÑO');s+=room(x+hall+w*.28+8,y+h-bottom+8,w*.28-16,bottom-16,'ESCALERA ↑');s+=room(x+hall+w*.56+8,y+h-bottom+8,w*.44-16,bottom-16,/terraza/i.test(needs)?'TERRAZA':'ESTAR');s+=door(x+hall,usableY+35) }
s+=`<line class="dim" x1="${x}" y1="${y-30}" x2="${x+w}" y2="${y-30}"/><text class="dimt" x="${x+w/2}" y="${y-38}">${L.toFixed(2)} m</text><line class="dim" x1="${x-35}" y1="${y}" x2="${x-35}" y2="${y+h}"/><text class="dimt" transform="translate(${x-48},${y+h/2}) rotate(-90)">${W.toFixed(2)} m</text>`;
s+=`<g transform="translate(875,85)"><text class="title" x="0" y="0" font-size="14">N</text><line class="thin" x1="0" y1="10" x2="0" y2="48"/><path d="M0 8 L-7 22 L7 22 Z" fill="#111"/></g>`;
s+=`<text class="note" x="180" y="545">Muros, puertas, ventanas, mobiliario, circulación y cotas representados de forma conceptual.</text></svg>`;return s}
function generate(){const p=build(),L=+$('profL').value,W=+$('profW').value,levels=+$('profLevels').value,rooms=+$('profRooms').value,baths=+$('profBaths').value,cars=+$('profCars').value,needs=$('profNeeds').value.trim();if(L<3||W<5){$('profMsg').textContent='Ingresa medidas válidas.';return}$('profMsg').textContent='✦ Diseñando zonificación, circulación y representación arquitectónica...';const count=levels===3?2:levels;let sheets='';for(let i=1;i<=count;i++)sheets+=`<div class="sheet">${plan(i,L,W,rooms,baths,cars,needs)}</div>`;if(levels===3)sheets+=`<div class="sheet">${plan(3,L,W,rooms,baths,cars,needs)}</div>`;const area=L*W;const built=count*area;$('profResult').innerHTML=`<div class="sheet-wrap">${sheets}</div><div class="tb"><div><b>PROYECTO</b><br>OFIELD AI</div><div><b>TERRENO</b><br>${L} × ${W} m</div><div><b>ESCALA</b><br>Gráfica 1:100</div><div><b>ESTADO</b><br>CONCEPTUAL</div></div><table class="areas"><tr><th>Cuadro de áreas / datos</th><th>Valor</th></tr><tr><td>Superficie del terreno</td><td>${area.toFixed(2)} m²</td></tr><tr><td>Niveles</td><td>${levels===3?'2 + roof garden':levels}</td></tr><tr><td>Recámaras</td><td>${rooms}</td></tr><tr><td>Baños</td><td>${baths}</td></tr><tr><td>Cochera</td><td>${cars} auto(s)</td></tr></table><p class="disclaimer">Plano conceptual: no sustituye proyecto ejecutivo, cálculo estructural, instalaciones, levantamiento topográfico, estudio de suelo, permisos ni revisión del reglamento local.</p>`;$('profMsg').textContent='✓ Plano arquitectónico conceptual generado.';$('profResult').dataset.plan=JSON.stringify({L,W,levels,rooms,baths,cars,needs,created:new Date().toISOString()})}
function save(){const r=$('profResult');if(!r?.dataset.plan){$('profMsg').textContent='Genera un plano primero.';return}let a=[];try{a=JSON.parse(localStorage.getItem('ofield_prof_plans')||'[]')}catch{}a.unshift(JSON.parse(r.dataset.plan));localStorage.setItem('ofield_prof_plans',JSON.stringify(a.slice(0,20)));$('profMsg').textContent='✓ Plano guardado.'}
function bind(){css();const b=$('openConceptPlan');if(b){b.onclick=e=>{e.preventDefault();e.stopPropagation();open()};b.removeAttribute('onclick')}document.addEventListener('click',e=>{if(e.target.closest('#openConceptPlan')){e.preventDefault();open()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();