const form=document.getElementById('projectForm');
const idea=document.getElementById('idea');
const type=document.getElementById('type');
const size=document.getElementById('size');
const budget=document.getElementById('budget');
const result=document.getElementById('resultado');
const resultBox=document.getElementById('resultBox');
const resultSummary=document.getElementById('resultSummary');
const message=document.getElementById('message');
const downloadBtn=document.getElementById('downloadBtn');
let lastProject='';
const templates={
 'Arquitectura':{goal:'Definir una propuesta espacial clara y viable.',steps:['Analizar terreno y necesidades','Definir programa arquitectónico','Organizar zonas públicas, privadas y de servicio','Establecer medidas y circulaciones','Seleccionar materiales y acabados','Preparar presupuesto y siguientes planos'],resources:['Plano o medidas del terreno','Programa de necesidades','Referencias visuales','Materiales y acabados','Herramienta de dibujo o modelado'],deliverable:'Anteproyecto organizado con programa, criterios, etapas y presupuesto inicial.'},
 'Proyecto escolar':{goal:'Convertir el tema en un proyecto con objetivos, investigación y entrega final.',steps:['Definir pregunta o problema','Investigar fuentes confiables','Organizar la información','Desarrollar la propuesta','Revisar y corregir','Preparar presentación final'],resources:['Fuentes de información','Material de investigación','Calendario de entrega','Herramientas de edición'],deliverable:'Estructura lista para desarrollar el proyecto escolar.'},
 'Negocio':{goal:'Convertir la idea en un modelo de negocio sencillo y accionable.',steps:['Definir cliente objetivo','Precisar producto o servicio','Investigar competencia','Calcular costos','Definir precio e ingresos','Crear una estrategia de lanzamiento'],resources:['Presupuesto inicial','Canales de venta','Propuesta de valor','Material promocional'],deliverable:'Plan inicial de negocio con próximos pasos.'},
 'Contenido / historia':{goal:'Transformar la idea creativa en una estructura de contenido producible.',steps:['Definir concepto y público','Crear personajes o elementos','Dividir la historia en partes','Planear escenas o capítulos','Definir recursos de producción','Preparar publicación'],resources:['Guion o escaleta','Personajes','Locaciones o recursos visuales','Calendario de producción'],deliverable:'Biblia inicial de contenido para comenzar la producción.'},
 'Otro proyecto':{goal:'Ordenar la idea en objetivos, etapas, recursos y un resultado concreto.',steps:['Definir objetivo','Dividir el trabajo en etapas','Identificar recursos','Estimar costos y tiempo','Ejecutar y revisar','Preparar resultado final'],resources:['Información del proyecto','Recursos disponibles','Presupuesto','Calendario'],deliverable:'Plan de acción inicial.'}
};
form.addEventListener('submit',e=>{e.preventDefault();const text=idea.value.trim();if(!text){message.textContent='Escribe primero una idea para tu proyecto.';idea.focus();return;}const t=templates[type.value];const dataSize=size.value.trim()||'No especificado';const dataBudget=budget.value.trim()||'No especificado';const steps=t.steps.map((x,i)=>`<li><strong>${i+1}.</strong> ${x}</li>`).join('');const resources=t.resources.map(x=>`<li>${x}</li>`).join('');resultSummary.textContent=`${type.value} · propuesta creada a partir de tu descripción.`;resultBox.innerHTML=`<div class="result-box"><div class="result-section"><h3>Idea analizada</h3><p>${escapeHtml(text)}</p><p><strong>Datos:</strong> ${escapeHtml(dataSize)} · <strong>Presupuesto:</strong> ${escapeHtml(dataBudget)}</p></div><div class="result-section"><h3>Objetivo recomendado</h3><p>${t.goal}</p></div><div class="result-section"><h3>Plan de trabajo</h3><ol>${steps}</ol></div><div class="result-section"><h3>Recursos necesarios</h3><ul>${resources}</ul></div><div class="result-section"><h3>Resultado esperado</h3><p>${t.deliverable}</p></div><div class="result-section"><h3>Próximo paso</h3><p>Empieza por definir con precisión el objetivo y reúne los datos que todavía falten. Después puedes desarrollar cada etapa con las futuras herramientas de Ofield AI.</p></div></div>`;lastProject=`OFIELD AI — PROYECTO GENERADO\n\nTipo: ${type.value}\nIdea: ${text}\nDatos: ${dataSize}\nPresupuesto: ${dataBudget}\n\nOBJETIVO\n${t.goal}\n\nPLAN DE TRABAJO\n${t.steps.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nRECURSOS\n${t.resources.map(x=>`- ${x}`).join('\n')}\n\nRESULTADO ESPERADO\n${t.deliverable}`;result.classList.remove('hidden');message.textContent='✓ Propuesta generada.';result.scrollIntoView({behavior:'smooth'});});
downloadBtn.addEventListener('click',()=>{if(!lastProject)return;const blob=new Blob([lastProject],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ofield-ai-proyecto.txt';a.click();URL.revokeObjectURL(url);});
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}