const API_URL='https://ofield-ai-api.luiseldorado110.workers.dev/';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const formatAnswer=t=>esc(t).replace(/^###\s+(.+)$/gm,'<h4>$1</h4>').replace(/^##\s+(.+)$/gm,'<h3>$1</h3>').replace(/^#\s+(.+)$/gm,'<h2>$1</h2>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>');
const money=v=>Number(v||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
function openPanel(panel){if(!panel)return;panel.classList.remove('hidden');panel.scrollIntoView({behavior:'smooth',block:'center'});}
function closePanel(panel){if(panel)panel.classList.add('hidden');}

// Generador principal
const form=$('projectForm');
if(form)form.addEventListener('submit',async e=>{e.preventDefault();const idea=$('idea').value.trim();const msg=$('message');if(!idea){msg.textContent='Escribe primero una idea para tu proyecto.';return}const type=$('type')?.value||'Otro proyecto';const details=`Tipo de proyecto: ${type}\nDatos: ${$('size')?.value||'No especificado'}\nPresupuesto: ${$('budget')?.value||'No especificado'}\nIdea: ${idea}`;msg.textContent='✦ Ofield AI está preparando tu proyecto...';const btn=form.querySelector('button[type="submit"]');if(btn)btn.disabled=true;try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea:details})});const d=await r.json();if(!r.ok||!d.result)throw Error();$('resultSummary').textContent=`${type} · propuesta generada con Ofield AI.`;$('resultBox').innerHTML=`<div class="result-box"><h3>Proyecto generado</h3><div class="ai-answer">${formatAnswer(d.result)}</div></div>`;$('resultado').classList.remove('hidden');msg.textContent='✓ Proyecto generado.';$('resultado').scrollIntoView({behavior:'smooth'});const h=JSON.parse(localStorage.getItem('ofieldProjects')||'[]');h.unshift({type,idea,size:$('size')?.value||'',budget:$('budget')?.value||'',answer:d.result,date:new Date().toLocaleString('es-MX')});localStorage.setItem('ofieldProjects',JSON.stringify(h.slice(0,8)));renderHistory();}catch(err){console.error(err);msg.textContent='No pudimos conectar con la IA. Revisa el Worker.'}finally{if(btn)btn.disabled=false}});

// Historial
function renderHistory(){const box=$('historyList');if(!box)return;const h=JSON.parse(localStorage.getItem('ofieldProjects')||'[]');box.innerHTML=h.length?h.map((p,i)=>`<article class="history-card"><div><span>${esc(p.type)}</span><h3>${esc(String(p.idea).slice(0,80))}</h3><small>${esc(p.date)}</small></div><button class="secondary history-open" data-i="${i}" type="button">Abrir →</button></article>`).join(''):'<p class="empty-history">Todavía no tienes proyectos guardados.</p>';box.querySelectorAll('.history-open').forEach(b=>b.onclick=()=>{const p=h[Number(b.dataset.i)];$('idea').value=p.idea;$('type').value=p.type;$('size').value=p.size||'';$('budget').value=p.budget||'';$('resultBox').innerHTML=`<div class="result-box"><h3>Proyecto recuperado</h3><div class="ai-answer">${formatAnswer(p.answer)}</div></div>`;$('resultado').classList.remove('hidden');$('resultado').scrollIntoView({behavior:'smooth'});});}
renderHistory();

// Calculadora de presupuesto
const budgetPanel=$('budgetPanel');
function addBudgetRow(name='',qty=1,price=0){const rows=$('budgetRows');if(!rows)return;const row=document.createElement('div');row.className='budget-row';row.innerHTML=`<input class="b-name" placeholder="Concepto" value="${esc(name)}"><input class="b-qty" type="number" min="0" step="0.01" value="${qty}"><input class="b-price" type="number" min="0" step="0.01" value="${price}"><strong class="b-sub">$0.00</strong><button type="button" class="secondary b-remove">×</button>`;rows.appendChild(row);row.querySelectorAll('input').forEach(x=>x.oninput=updateBudget);row.querySelector('.b-remove').onclick=()=>{row.remove();updateBudget()};updateBudget();}
function updateBudget(){const rows=$('budgetRows');if(!rows)return;let total=0;rows.querySelectorAll('.budget-row').forEach(r=>{const sub=(Number(r.querySelector('.b-qty').value)||0)*(Number(r.querySelector('.b-price').value)||0);total+=sub;r.querySelector('.b-sub').textContent=money(sub)});$('budgetSubtotal').textContent=money(total);const pct=Number($('contingency')?.value)||0;$('budgetTotal').textContent=money(total*(1+pct/100));}
$('openBudget')?.addEventListener('click',()=>{openPanel(budgetPanel);if(!$('budgetRows').children.length){addBudgetRow('Material');addBudgetRow('Mano de obra');addBudgetRow('Otros')}});
$('closeBudget')?.addEventListener('click',()=>closePanel(budgetPanel));$('addBudgetRow')?.addEventListener('click',()=>addBudgetRow());$('clearBudget')?.addEventListener('click',()=>{$('budgetRows').innerHTML='';updateBudget()});$('contingency')?.addEventListener('input',updateBudget);

// Plan de trabajo
const planPanel=$('planPanel');$('openPlan')?.addEventListener('click',()=>openPanel(planPanel));$('closePlan')?.addEventListener('click',()=>closePanel(planPanel));$('generatePlan')?.addEventListener('click',async()=>{const idea=$('planIdea').value.trim();const msg=$('planMessage');if(!idea){msg.textContent='Escribe primero qué quieres realizar.';return}msg.textContent='✦ Ofield AI está creando tu plan...';$('generatePlan').disabled=true;try{const prompt=`Crea un plan de trabajo personalizado para: ${idea}\nTiempo: ${$('planTime').value||'no especificado'}\nPresupuesto: ${$('planBudget').value||'no especificado'}\nIncluye etapas, tareas, tiempos, recursos, costos, riesgos y próximos pasos. En español.`;const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea:prompt})});const d=await r.json();if(!r.ok||!d.result)throw Error();$('planResult').innerHTML=formatAnswer(d.result);msg.textContent='✓ Plan generado.'}catch(e){msg.textContent='No se pudo generar el plan.'}finally{$('generatePlan').disabled=false}});

// Materiales
const materialsPanel=$('materialsPanel');$('openMaterials')?.addEventListener('click',()=>openPanel(materialsPanel));$('closeMaterials')?.addEventListener('click',()=>closePanel(materialsPanel));$('calculateMaterials')?.addEventListener('click',()=>{const L=Number($('matLength').value)||0,W=Number($('matWidth').value)||0,H=Number($('matHeight').value)||0,O=Number($('matOpenings').value)||0;if(L<=0||W<=0||H<=0){$('materialsResult').innerHTML='<strong>Ingresa largo, ancho y altura mayores que cero.</strong>';return}const wall=Math.max(0,2*(L+W)*H-O),blocks=Math.ceil(wall*12.5*1.08),mortar=wall*.02*1.1,slab=L*W*.1;$('materialsResult').innerHTML=`<h3>Estimación inicial</h3><p><strong>Área de muros:</strong> ${wall.toFixed(2)} m²</p><p><strong>Block:</strong> ${blocks.toLocaleString('es-MX')} piezas aprox.</p><p><strong>Mortero:</strong> ${mortar.toFixed(2)} m³ aprox.</p><p><strong>Concreto para losa de 10 cm:</strong> ${slab.toFixed(2)} m³ aprox.</p><small>⚠️ Estimación orientativa; requiere revisión profesional.</small>`});

// Analizador de viabilidad — corregido y sin depender de código inline
const feasibilityPanel=$('feasibilityPanel');
$('openFeasibility')?.addEventListener('click',()=>openPanel(feasibilityPanel));
$('closeFeasibility')?.addEventListener('click',()=>closePanel(feasibilityPanel));
$('analyzeFeasibility')?.addEventListener('click',async()=>{const idea=$('feasibilityIdea').value.trim();const msg=$('feasibilityMessage');const out=$('feasibilityResult');if(!idea){msg.textContent='Escribe primero qué quieres realizar.';$('feasibilityIdea').focus();return}msg.textContent='✦ Ofield AI está analizando la viabilidad...';$('analyzeFeasibility').disabled=true;try{const prompt=`Analiza la viabilidad de este proyecto: ${idea}\nPresupuesto disponible: ${$('feasibilityBudget').value.trim()||'no especificado'}\nTiempo disponible: ${$('feasibilityTime').value.trim()||'no especificado'}\nResponde en español. Incluye: veredicto de viabilidad (ALTA, MEDIA o BAJA), puntuación de 0 a 100, qué sí es posible, limitaciones, riesgos, presupuesto recomendado, tiempo recomendado, cambios para hacerlo viable, prioridades y próximos pasos. No inventes precios exactos si faltan datos y explica los supuestos.`;const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea:prompt})});const d=await r.json();if(!r.ok||!d.result)throw Error(d.error||'Sin resultado');out.innerHTML=`<div class="result-box"><h3>✓ Análisis de viabilidad</h3><div class="ai-answer">${formatAnswer(d.result)}</div></div>`;msg.textContent='✓ Análisis terminado.'}catch(e){console.error(e);msg.textContent='No se pudo completar el análisis. Revisa la conexión con Ofield AI.'}finally{$('analyzeFeasibility').disabled=false}});

// Acciones de resultado
$('copyBtn')?.addEventListener('click',async()=>{const text=$('resultBox')?.innerText||'';if(text){await navigator.clipboard.writeText(text);$('copyBtn').textContent='✓ Copiado';setTimeout(()=>$('copyBtn').textContent='⧉ Copiar',1500)}});
$('printBtn')?.addEventListener('click',()=>window.print());
$('downloadBtn')?.addEventListener('click',()=>{const text=$('resultBox')?.innerText||'';if(!text)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download='ofield-ai-proyecto.txt';a.click();});